### Numpy Assignment For Sir Qasim

In [2]:
import numpy as np

In [2]:
np.__version__

'1.17.0'

## 1D Array

In [3]:
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
b = np.array([4.0,5.0,6.0])

In [6]:
print(b)

[4. 5. 6.]


In [7]:
# finding dimension
a.ndim
b.ndim

1

In [8]:
# finding Shape
a.shape

(3,)

In [12]:
c = np.array([11,22,33,44,55], dtype='int16')

In [10]:
c.shape

(5,)

In [13]:
c

array([11, 22, 33, 44, 55], dtype=int16)

In [18]:
# getting type of array
print("A type ", end="")
print(a.dtype)
print("B type ", end="")
print(b.dtype)
print("C type ", end="")
print(c.dtype)

A type int32
B type float64
C type int16


In [19]:
# getting Size
print("A size ", end="")
print(a.itemsize)
print("B size ", end="")
print(b.itemsize)
print("C size ", end="")
print(c.itemsize)

A size 4
B size 8
C size 2


In [21]:
# getting total Size
print("A size ", end="")
print(a.nbytes)
print("B size ", end="")
print(b.nbytes)
print("C size ", end="")
print(c.nbytes)

A size 12
B size 24
C size 10


## 2D Array

In [22]:
a = np.array([[1,2,3],[4,5,6]])

In [23]:
print(a)

[[1 2 3]
 [4 5 6]]


In [26]:
a.dtype

dtype('int32')

In [27]:
a.itemsize

4

In [28]:
a.shape

(2, 3)

In [29]:
a.ndim

2

## 3D Array

In [32]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [33]:
a.ndim

3

In [34]:
a.shape

(2, 2, 3)

In [35]:
a.dtype

dtype('int32')

In [36]:
a.itemsize

4

# Accessing/Changing specific elements , rows, columns

In [45]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [38]:
a.shape

(2, 7)

In [39]:
# getting a specific element [r,c]
a[1,5]

13

In [42]:
a[0, 1:6:2]

array([2, 4, 6])

In [40]:
# getting a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
# getting a specific coulmn
a[:,2]

array([ 3, 10])

In [46]:
# changing element
print("orignal Array : \n", a)
a[1,5] = 20
print("After Changing second row sixth element :\n", a )

orignal Array : 
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
After Changing second row sixth element :
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [47]:
# changing column
a[:,1] = 6
print(a)

[[ 1  6  3  4  5  6  7]
 [ 8  6 10 11 12 20 14]]


In [48]:
a[:,2] = [22,23]
print(a)

[[ 1  6 22  4  5  6  7]
 [ 8  6 23 11 12 20 14]]


In [49]:
# Using 3D Array
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [50]:
a[0,1,1]

5

In [51]:
a[:,1,:] = [[9,9],[8,8]]
print(a)

ValueError: cannot copy sequence with size 2 to array axis with dimension 3

In [52]:
a[:,1,:] = [[9,9,9],[8,8,8]]
print(a)

[[[1 2 3]
  [9 9 9]]

 [[7 8 9]
  [8 8 8]]]


## initializing Different Types of Array

In [6]:
# All zeros Matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# All ones Matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Any other Number
np.full((3,3), 25)

array([[25, 25, 25],
       [25, 25, 25],
       [25, 25, 25]])

In [13]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])
np.full_like(a,4)

array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]])

In [14]:
# Random decimal number
np.random.rand(4,2)

array([[0.79504544, 0.12789629],
       [0.65395691, 0.58481585],
       [0.10848135, 0.96423212],
       [0.58099136, 0.39813451]])

In [15]:
# Random Integer number
np.random.randint(7)

5

In [16]:
np.random.randint(10, size=(3,3))

array([[2, 0, 4],
       [5, 3, 1],
       [9, 6, 4]])

In [17]:
# The identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [21]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [24]:
# printing 
# 1, 1, 1, 1, 1
# 1, 0, 0, 0, 1
# 1, 0, 9, 0, 1
# 1, 0, 0, 0, 1
# 1, 1, 1, 1, 1

output = np.ones((5,5), dtype='int32')
z = np.zeros((3,3))
z[1,1] = 9
output[1:-1,1:-1] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Copying Array

In [25]:
a = np.array([1,2,3])
print(a)
b = a.copy()
b[0] = 100
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [26]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [27]:
a + 2

array([3, 4, 5, 6])

In [28]:
a - 2

array([-1,  0,  1,  2])

In [29]:
a * 2

array([2, 4, 6, 8])

In [30]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [31]:
a = np.array([1,2,3,4])
b = np.array([1,0,1, 0])
a + b

array([2, 2, 4, 4])

In [32]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [34]:
# Sin , Cos, Tan
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [35]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [36]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

### Linear Algebra

In [38]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [39]:
c = np.identity(3)
np.linalg.det(c)
    

1.0

### Statistics

In [42]:
stats = np.array([[1,2,3],[4,5,6]])

In [43]:
np.min(stats)

1

In [44]:
np.max(stats, axis=1)

array([3, 6])

In [45]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganizing Array

In [46]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(2,2,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
# Vertically stacking vectors
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.vstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
h1 = np.ones((2,2))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])